### ISSUE TITLE
Issues when import data using Data Import

### ISSUE THREAD

**Issue by magic-overflow** [zerodhatech/Frappe-attachments-s3#13]
> Traceback (most recent call last):
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
>     response = frappe.handler.handle()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
>     data = execute_cmd(cmd)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
>     return frappe.call(method, **frappe.form_dict)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
>     return fn(*args, **newargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
>     doc.save()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
>     return self._save(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 290, in _save
>     self.run_before_save_methods()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
>     self.run_method("validate")
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/data_import.py", line 28, in validate
>     upload(data_import_doc=self, from_data_import="Yes", validate_template=True)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/data_import/importer.py", line 267, in upload
>     fname, fcontent = get_file(data_import_doc.import_file)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 278, in get_file
>     file_path = get_file_path(fname)
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/file_manager.py", line 305, in get_file_path
>     frappe.throw(_("There is some problem with the file url: {0}").format(file_path))
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 323, in throw
>     msgprint(msg, raise_exception=exc, title=title, indicator='red')
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 309, in msgprint
>     _raise_exception()
>   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 282, in _raise_exception
>     raise raise_exception(encode(msg))
> ValidationError: There is some problem with the file url: https://s3.us-west-2.amazonaws.com/abc/abc/2018/05/11/Data Import/N0ICE3V2_CustomerShop888a80csv

The url is not the right format in ERPNEXT.
https://github.com/frappe/frappe/blob/fc99d691d13cfe79f393e9a66c034c7280c97c09/frappe/utils/file_manager.py#L336

**Comment by Ramesh7128** [comment]
fixed. Data import upload alone wont be pushed to s3.
